### ISSUE TITLE
コードレビュー

### ISSUE THREAD

**Issue by equal-l2** [uoo38/simple_http_server#1]
コードに改善できそうな点を見つけられたらここに書いていきます。
CC @pfpacket

**Comment by equal-l2** [comment]
https://github.com/uoo38/SimpleHttpServer/blob/c08db3187b8fcd2dc58f4ee3e6424d7d22a2a95f/Cargo.toml#L2

強制ではありませんが、コンベンションとしてcrateの名前はスネークケースが推奨されています。
(Cargoも警告を出します)

---

https://github.com/uoo38/SimpleHttpServer/blob/c08db3187b8fcd2dc58f4ee3e6424d7d22a2a95f/src/main.rs#L9-L12

`Ok`ならそのまま、`Err`の時は(エラーの値を利用して)別処理をする、という処理は[`Result::unwrap_or_else`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_else)を使って書くことができます。

```rust
let s = str::from_utf8(&buffer).unwrap_or_else(|e| panic!("Invalid UTF-8 sequence: {}", e));
``` 

`unwrap_or_else`は本来、元の`Result`型の`Ok`に入る型を返す必要がありますが、`panic!()`は[`!`(*never type*)](https://doc.rust-lang.org/std/primitive.never.html)という何にでもなれる型を返すので問題なくコンパイルできています。

---

https://github.com/uoo38/SimpleHttpServer/blob/c08db3187b8fcd2dc58f4ee3e6424d7d22a2a95f/src/main.rs#L15-L17

`write`は割り込みなどで邪魔されてバッファを書き込み切らずに返る場合があります。
`write`の返り値を見て全て書き込まれたことを確認してもいいですが、特別に事情がなければ`write_all`を使う方がいいです。
(これはRustのリンタの一種である[Clippy](https://github.com/rust-lang/rust-clippy)が指摘してくれました)

**Comment by pfpacket** [comment]
https://github.com/uoo38/simple_http_server/blob/7a8cc75e1e01b31969945f0852aef998241110b1/src/main.rs#L9-L12

`let s = str::from_utf8(&buffer).expect("Invalid UTF-8 sequence");` でよいかと。ちゃんとエラーメッセージが `{:?}` (Debug) で表示されます。僕はこうしたほうが短くてコードが見やすいと感じました。究極的には好みですが...

あとは青シャツがあらかた指摘しているので、僕からは以上です。

**Comment by equal-l2** [comment]
https://github.com/uoo38/simple_http_server/blob/7a8cc75e1e01b31969945f0852aef998241110b1/src/main.rs#L8

`read_exact` は「バッファが全て埋まるまでブロックする」ので、今回の場合だと1024バイト読むまで戻ってきません。
おそらく意図している動作には`read`を使うべきだと思います。

**Comment by equal-l2** [comment]
テストの件ですが、[Rocket](https://github.com/SergioBenitez/Rocket/blob/master/examples/testing/src/main.rs)や[actix-web](https://github.com/actix/actix-web/blob/master/tests/test_httpserver.rs)では自前のHTTPクライアントで実際に通信してテストしています。

悟空と話した感じでは、簡単にテストをするなら複数スレッドで、あるスレッドでサーバを建てて、別スレッドで`TcpStream`を使ってリクエストを送ればいいんじゃないか、という感じです。

**Comment by pfpacket** [comment]
> https://github.com/uoo38/simple_http_server/blob/7a8cc75e1e01b31969945f0852aef998241110b1/src/main.rs#L8
> 
> `read_exact` は「バッファが全て埋まるまでブロックする」ので、今回の場合だと1024バイト読むまで戻ってきません。
> おそらく意図している動作には`read`を使うべきだと思います。

どんなクライアントを想定してるのかわかりませんが、今回は1024バイトかならずくると思ってましたが...

**Comment by equal-l2** [comment]
HTTPサーバということだったので、curlとFirefoxでそれぞれGETを投げましたが、`read_exact`だとうまく動作しませんでした。

**Comment by sanopy** [comment]
確かに `read_exact` だとレスポンスが返ってきませんね。 `read` に戻すべきだったっぽい？

**Comment by pfpacket** [comment]
> HTTPサーバということだったので、curlとFirefoxでそれぞれGETを投げましたが、`read_exact`だとうまく動作しませんでした。

ちゃんとHTTPサーバーやるなら、socketプログラミングの基本通り、HTTPリクエストをパースしながらリクエストのデリミターを探しながらリードを繰り返すしかないです
